let homeId=null,awayId=null,teams=UNIQUE_TEAMS;
const $=id=>document.getElementById(id); function fmt(x){return Number(x).toFixed(2);} function pct(x){return (x*100).toFixed(1)+'%';}
function logo(t){return `https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/${t.logo}.png`;}
function renderTeams(){const h=$('homeTeams'),a=$('awayTeams');h.innerHTML='';a.innerHTML='';teams.forEach(t=>{h.appendChild(teamButton(t,'home'));a.appendChild(teamButton(t,'away'));});}
function teamButton(t,side){const b=document.createElement('button');b.className='teamBtn';b.type='button';b.dataset.id=t.id;b.innerHTML=`<img src="${logo(t)}" alt=""><span>${t.short}</span>`;b.onclick=()=>selectTeam(t,side);return b;}
function selectTeam(t,side){if(side==='home')homeId=t.id;else awayId=t.id; document.querySelectorAll(`.teams button`).forEach(b=>b.classList.remove('selected')); if(homeId)document.querySelector(`#homeTeams button[data-id="${homeId}"]`)?.classList.add('selected'); if(awayId)document.querySelector(`#awayTeams button[data-id="${awayId}"]`)?.classList.add('selected'); $('homeSelected').textContent=teams.find(x=>x.id===homeId)?.name||'Selecciona local'; $('awaySelected').textContent=teams.find(x=>x.id===awayId)?.name||'Selecciona visitante'; $('analyzeBtn').disabled=!(homeId&&awayId&&homeId!==awayId);}
function row(label,val){return `<div class="row"><span>${label}</span><strong>${val}</strong></div>`;}
function statCard(t,p){return `<div class="teamTitle"><img src="${logo(t)}"><b>${t.name}</b></div>${row('Temporada',`${p.season.n} juegos · ${fmt(p.season.rsG)} RS / ${fmt(p.season.raG)} RA`)}${row('Últimos 10',`${p.l10.n} juegos · ${fmt(p.l10.rsG)} / ${fmt(p.l10.raG)}`)}${row('Primeras 3',`${p.f3.n} juegos · ${fmt(p.f3.rsG)} / ${fmt(p.f3.raG)}`)}${row('Nivel ponderado',`${fmt(p.rs)} RS · ${fmt(p.ra)} RA`)}`;}
async function analyze(){const date=$('date').value; if(!date||!homeId||!awayId)return; $('status').textContent='Cargando datos MLB…'; $('analyzeBtn').disabled=true; try{const season=new Date(date+'T12:00:00').getFullYear();const d=await getTeamProfiles(homeId,awayId,season,date);const ht=teams.find(t=>t.id===homeId),at=teams.find(t=>t.id===awayId);const home={rs:d.hp.rs,ra:d.hp.ra,homeRS:d.hHome.rsG||d.hp.rs,homeRA:d.hHome.raG||d.hp.ra};const away={rs:d.ap.rs,ra:d.ap.ra,awayRS:d.aAway.rsG||d.ap.rs,awayRA:d.aAway.raG||d.ap.ra};const m=calculateModel(ht.name,at.name,home,away,d.lg);render(ht,at,d,m,date);$('status').textContent='Datos cargados correctamente.';}catch(e){$('status').textContent='No se pudieron cargar los datos: '+e.message;}finally{$('analyzeBtn').disabled=!(homeId&&awayId&&homeId!==awayId);}}
function render(ht,at,d,m,date){$('result').classList.remove('hidden');$('pick').textContent=m.options[0].label;$('pickProb').textContent=pct(m.options[0].p);$('matchNote').textContent=`${date} · LG_R ${fmt(d.lg)} · SD ${MLB_CONFIG.runSD}`;$('homeStats').innerHTML=statCard(ht,d.hp);$('awayStats').innerHTML=statCard(at,d.ap);$('matchupRows').innerHTML=row(ht.name+' Pythagorean',pct(m.ph))+row(at.name+' Pythagorean',pct(m.pa))+row('Probabilidad neutral · '+ht.short,pct(m.neutral))+row('Probabilidad con localía · '+ht.short,pct(m.local));$('runRows').innerHTML=row(ht.name,fmt(m.projHome))+row(at.name,fmt(m.projAway))+row('Total proyectado',fmt(m.total))+row('Línea total',m.line);$('marketRows').innerHTML=row('Over '+m.line,pct(m.over))+row('Under '+m.line,pct(m.under))+row(m.favorite+' -1.5',pct(m.fav15))+row((m.favorite===ht.name?at.name:ht.name)+' +1.5',pct(m.dog15));$('options').innerHTML=m.options.map((o,i)=>`<div class="option ${i===0?'top':''}"><div><b>${o.label}</b><small>${i===0?'PICK DEL MODELO':''}</small></div><strong>${pct(o.p)}</strong></div>`).join('');window.scrollTo({top:$('result').offsetTop-10,behavior:'smooth'});}
function init(){const today=new Date(); $('date').value=today.toISOString().slice(0,10);renderTeams();$('analyzeBtn').onclick=analyze;}
window.addEventListener('DOMContentLoaded',init);
